#!/usr/bin/env bash
#
# migrate-relocate-prefs.sh - 個人好み 7 キーの project → user-global 移動提案
#
# 使用方法:
#   ./migrate-relocate-prefs.sh detect [--dry-run]
#   ./migrate-relocate-prefs.sh move <key> [--overwrite] [--dry-run]
#   ./migrate-relocate-prefs.sh keep <key> [--dry-run]
#
# 環境変数:
#   AIDLC_PROJECT_ROOT       - project ルート（既定: git rev-parse --show-toplevel）
#   AIDLC_USER_GLOBAL_PATH   - user-global ファイルパス（既定: ${HOME}/.aidlc/config.toml）
#
# 出力（タブ区切り単一形式 / stdout）:
#   detected\t<key>\t<value>\t<user_global_conflict:true|false>
#   summary\ttotal\t<N>
#   move\t<key>\t<value>\tfrom_project\tto_user_global
#   keep\t<key>
#   dry-run:detected\t...   dry-run:move\t...   dry-run:keep\t...
#
# 出力（stderr）:
#   warn:<type>:<detail>     - 処理継続可能な警告（exit 0）
#   error:<type>:<detail>    - 致命エラー（exit 2）
#
# 終了コード:
#   0 - 正常完了（detect 0 件含む）
#   2 - エラー（引数不正 / ファイル不在 / dasel 未インストール / 不正キー等）

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"

# toml-reader.sh ライブラリ読み込み
# shellcheck source=/dev/null
source "${REPO_ROOT}/skills/aidlc/scripts/lib/toml-reader.sh"

# 個人好み 7 キー集合（Unit 001 SoT との同期は tests/aidlc-migrate-prefs/key-set-sync.bats で検証）
readonly INDIVIDUAL_PREFERENCE_KEYS=(
  "rules.reviewing.mode"
  "rules.reviewing.tools"
  "rules.automation.mode"
  "rules.git.squash_enabled"
  "rules.git.ai_author"
  "rules.git.ai_author_auto_detect"
  "rules.linting.enabled"
)

# キーごとの値型ホワイトリスト（セキュリティ: 不正値による TOML 注入を防止）
# 形式: "key|type[:enum1,enum2,...]"
readonly KEY_VALUE_TYPES=(
  "rules.reviewing.mode|enum:recommend,required"
  "rules.reviewing.tools|string_array"
  "rules.automation.mode|enum:manual,semi_auto,full_auto"
  "rules.git.squash_enabled|boolean"
  "rules.git.ai_author|string"
  "rules.git.ai_author_auto_detect|boolean"
  "rules.linting.enabled|boolean"
)

# プロジェクト / user-global パス解決
_resolve_paths() {
  AIDLC_PROJECT_ROOT="${AIDLC_PROJECT_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null)}" || {
    echo "error:project-root-not-found" >&2
    exit 2
  }
  if [[ ! -d "${AIDLC_PROJECT_ROOT}" ]]; then
    echo "error:project-root-not-found:${AIDLC_PROJECT_ROOT}" >&2
    exit 2
  fi
  PROJECT_CONFIG="${AIDLC_PROJECT_ROOT}/.aidlc/config.toml"
  USER_GLOBAL_PATH="${AIDLC_USER_GLOBAL_PATH:-${HOME}/.aidlc/config.toml}"
}

# 個人好み 7 キー集合に属するか判定
_is_individual_preference_key() {
  local target="$1"
  local k
  for k in "${INDIVIDUAL_PREFERENCE_KEYS[@]}"; do
    if [[ "$k" == "$target" ]]; then
      return 0
    fi
  done
  return 1
}

# キーから section と leaf を抽出
# 例: rules.reviewing.mode -> section="rules.reviewing", leaf="mode"
_split_key() {
  local key="$1"
  local section="${key%.*}"
  local leaf="${key##*.}"
  echo "${section}|${leaf}"
}

# 一時ファイルクリーンアップ
declare -a _cleanup_files=()
_cleanup() {
  local f
  for f in "${_cleanup_files[@]}"; do
    [[ -f "$f" ]] && \rm -f "$f" 2>/dev/null
  done
}
trap _cleanup EXIT

_mktmp() {
  local tmp
  tmp=$(mktemp) || { echo "error:mktmp-failed" >&2; exit 2; }
  _cleanup_files+=("$tmp")
  echo "$tmp"
}

# sed/awk → tmp → mv の安全な書き込みパターン
_safe_transform() {
  local target="$1"
  shift
  local tmp
  tmp=$(_mktmp)
  "$@" "$target" > "$tmp" && \mv "$tmp" "$target"
}

# project から指定 section/leaf 行を削除（葉キー = 行のみ）
# section 内の指定 leaf 行を削除し、空セクションでも [section] ヘッダは残す
_delete_key_in_file() {
  local file="$1"
  local section="$2"
  local leaf="$3"

  if [[ ! -f "$file" ]]; then
    echo "error:file-not-found:${file}" >&2
    return 2
  fi

  # awk で [section] ... [次のセクション] の範囲内の `leaf =` 行を削除
  _safe_transform "$file" awk -v sec="[${section}]" -v lf="${leaf}" '
    BEGIN { in_section = 0 }
    {
      if ($0 == sec) {
        in_section = 1
        print
        next
      }
      if (in_section && /^\[/ && $0 != sec) {
        in_section = 0
      }
      if (in_section && $0 ~ "^[[:space:]]*"lf"[[:space:]]*=") {
        next
      }
      print
    }
  '
}

# user-global ファイルに section + leaf 行を追記
# section が既存しない場合は新規追加
_append_key_to_file() {
  local file="$1"
  local section="$2"
  local leaf="$3"
  local value="$4"

  # ファイル不在: 最小ヘッダ付きで新規作成
  if [[ ! -f "$file" ]]; then
    mkdir -p "$(dirname "$file")"
    cat > "$file" <<HEADER
# AI-DLC user-global config
# (auto-generated by migrate-relocate-prefs.sh)

HEADER
  fi

  # section が存在しない場合、追加
  if ! grep -q "^\[${section//./\\.}\]" "$file"; then
    printf '\n[%s]\n%s = %s\n' "$section" "$leaf" "$value" >> "$file"
  else
    # section は存在、leaf を section 配下に追加
    # awk で section 内の最後に挿入する
    _safe_transform "$file" awk -v sec="[${section}]" -v lf="${leaf}" -v val="${value}" '
      BEGIN { in_section = 0; printed = 0 }
      {
        if ($0 == sec) {
          in_section = 1
          print
          next
        }
        if (in_section && /^\[/ && $0 != sec) {
          if (!printed) {
            print lf " = " val
            printed = 1
          }
          in_section = 0
        }
        print
      }
      END {
        if (in_section && !printed) {
          print lf " = " val
        }
      }
    '
  fi
}

# user-global の同名キーを検出
# 戻り値: 0=存在, 1=不在
_user_global_has_key() {
  local key="$1"
  if [[ ! -f "${USER_GLOBAL_PATH}" ]]; then
    return 1
  fi
  if aidlc_read_toml "${USER_GLOBAL_PATH}" "$key" >/dev/null 2>&1; then
    return 0
  fi
  return 1
}

# project から指定キーの値を取得（空または不在は空文字を返し非 0 終了）
# 配列値の場合は dasel 出力（`['codex']` 等）をそのまま返す
_read_project_value() {
  local key="$1"
  if [[ ! -f "${PROJECT_CONFIG}" ]]; then
    return 1
  fi
  aidlc_read_toml "${PROJECT_CONFIG}" "$key" 2>/dev/null
}

# キーから値型を取得
# 戻り値: "boolean" / "enum:val1,val2,..." / "string" / "string_array"、未定義は空文字
_get_value_type_for_key() {
  local key="$1"
  local entry
  for entry in "${KEY_VALUE_TYPES[@]}"; do
    local k="${entry%%|*}"
    local t="${entry#*|}"
    if [[ "$k" == "$key" ]]; then
      printf '%s' "$t"
      return 0
    fi
  done
  return 1
}

# 値が制御文字 / 改行を含むか判定
# 戻り値: 0=安全 / 1=危険
_value_has_unsafe_chars() {
  local v="$1"
  # 改行・タブ・制御文字（0x00-0x1F, 0x7F）を含む場合は危険
  # タブ (0x09) もタブ区切り出力契約を壊すため除去対象に含める
  local sanitized
  sanitized="$(printf '%s' "$v" | LC_ALL=C tr -d '\000-\037\177')"
  if [[ "${#sanitized}" -ne "${#v}" ]]; then
    return 1
  fi
  return 0
}

# 文字列の TOML リテラルエスケープ（"" と \ をエスケープ）
_toml_escape_string() {
  local v="$1"
  # \ -> \\ 、" -> \"
  v="${v//\\/\\\\}"
  v="${v//\"/\\\"}"
  printf '%s' "$v"
}

# 値が型ホワイトリストに合致するか検証 + TOML 形式に正規化
# 引数: $1 = key, $2 = raw_value（aidlc_read_toml 出力）
# stdout: 正規化済み TOML リテラル
# 戻り値: 0=成功 / 2=値型不正 or 危険文字混入
_validate_and_normalize_value() {
  local key="$1"
  local v="$2"
  local type
  type="$(_get_value_type_for_key "$key")" || {
    echo "error:invalid-key:${key}" >&2
    return 2
  }

  # 危険文字（改行・制御文字）混入チェック
  if ! _value_has_unsafe_chars "$v"; then
    echo "error:invalid-value:${key}:control-char" >&2
    return 2
  fi

  case "$type" in
    boolean)
      if [[ "$v" != "true" && "$v" != "false" ]]; then
        echo "error:invalid-value:${key}:expected-boolean" >&2
        return 2
      fi
      printf '%s' "$v"
      ;;
    enum:*)
      local enums="${type#enum:}"
      local IFS=','
      local found="false"
      local e
      for e in $enums; do
        if [[ "$v" == "$e" ]]; then
          found="true"
          break
        fi
      done
      if [[ "$found" != "true" ]]; then
        echo "error:invalid-value:${key}:not-in-enum:${enums}" >&2
        return 2
      fi
      printf '"%s"' "$v"
      ;;
    string)
      # TOML エスケープ（" と \ をエスケープ）
      local escaped
      escaped="$(_toml_escape_string "$v")"
      printf '"%s"' "$escaped"
      ;;
    string_array)
      # dasel 出力: ['codex'] または ['codex','claude']
      # シングルクォートをダブルクォートに置換し、各要素を TOML エスケープ
      if [[ ! "$v" =~ ^\[.*\]$ ]]; then
        echo "error:invalid-value:${key}:expected-array" >&2
        return 2
      fi
      # 内部要素にも厳密性を求める（[\"a\", \"b\"] 形式に正規化）
      # 簡易版: シングルクォートをダブルクォートに置換、要素中の「危険文字」は弾く
      local normalized="${v//\'/\"}"
      # 配列要素を分解して個別エスケープ（bash 3.2 互換: 負のインデックスを使わない）
      local inner="${normalized#[}"
      inner="${inner%]}"
      # カンマで分割（個人好みキーの想定値は単純、`['codex']` / `['codex','claude']` 等）
      local out="["
      local first="true"
      local elem
      local IFS_BAK="$IFS"
      IFS=','
      # shellcheck disable=SC2206
      local elements=( $inner )
      IFS="$IFS_BAK"
      for elem in "${elements[@]}"; do
        # 前後空白除去
        elem="${elem## }"
        elem="${elem%% }"
        # ダブルクォート除去
        elem="${elem#\"}"
        elem="${elem%\"}"
        # 危険文字混入チェック
        if ! _value_has_unsafe_chars "$elem"; then
          echo "error:invalid-value:${key}:array-element-control-char" >&2
          return 2
        fi
        local elem_escaped
        elem_escaped="$(_toml_escape_string "$elem")"
        if [[ "$first" == "true" ]]; then
          out="${out}\"${elem_escaped}\""
          first="false"
        else
          out="${out}, \"${elem_escaped}\""
        fi
      done
      out="${out}]"
      printf '%s' "$out"
      ;;
    *)
      echo "error:unknown-value-type:${type}" >&2
      return 2
      ;;
  esac
  return 0
}

# ─── サブコマンド: detect ───────────────────────────

cmd_detect() {
  local dry_run="$1"
  local prefix=""
  if [[ "$dry_run" == "true" ]]; then
    prefix="dry-run:"
  fi

  if [[ ! -f "${PROJECT_CONFIG}" ]]; then
    echo "error:project-config-not-found:${PROJECT_CONFIG}" >&2
    return 2
  fi

  local count=0
  local key value conflict
  for key in "${INDIVIDUAL_PREFERENCE_KEYS[@]}"; do
    if value="$(_read_project_value "$key")" && [[ -n "${value}" || "${value}" == "" ]]; then
      # aidlc_read_toml が exit 0 を返した = キー存在
      if [[ -z "$value" ]]; then
        # 空文字値（rules.git.ai_author = "" 等）も検出対象
        :
      fi
      if _user_global_has_key "$key"; then
        conflict="true"
      else
        conflict="false"
      fi
      printf '%sdetected\t%s\t%s\t%s\n' "$prefix" "$key" "$value" "$conflict"
      count=$((count + 1))
    fi
  done
  printf '%ssummary\ttotal\t%d\n' "$prefix" "$count"
  return 0
}

# ─── サブコマンド: move ─────────────────────────────

cmd_move() {
  local key="$1"
  local overwrite="$2"
  local dry_run="$3"
  local prefix=""
  if [[ "$dry_run" == "true" ]]; then
    prefix="dry-run:"
  fi

  if ! _is_individual_preference_key "$key"; then
    echo "error:invalid-key:${key}" >&2
    return 2
  fi

  if [[ ! -f "${PROJECT_CONFIG}" ]]; then
    echo "error:project-config-not-found:${PROJECT_CONFIG}" >&2
    return 2
  fi

  local value
  value="$(_read_project_value "$key")" || {
    echo "error:key-not-found:${key}" >&2
    return 2
  }

  # user-global 同名キー検出
  if _user_global_has_key "$key"; then
    if [[ "$overwrite" != "true" ]]; then
      echo "warn:user-global-key-exists:${key}" >&2
      return 0
    fi
  fi

  # dry-run の場合は出力のみで実書き込みなし
  if [[ "$dry_run" == "true" ]]; then
    printf '%smove\t%s\t%s\tfrom_project\tto_user_global\n' "$prefix" "$key" "$value"
    return 0
  fi

  # 値型ホワイトリスト検証 + TOML 形式正規化（セキュリティ: 不正値による TOML 注入を防止）
  local normalized
  if ! normalized="$(_validate_and_normalize_value "$key" "$value")"; then
    return 2
  fi

  # 実書き込み: project からの削除 + user-global への追記（または上書き）
  local section_leaf section leaf
  section_leaf="$(_split_key "$key")"
  section="${section_leaf%|*}"
  leaf="${section_leaf#*|}"

  # トランザクション化: 両ファイルのバックアップを取り、いずれか失敗時はロールバック
  local project_backup ug_backup
  project_backup="$(_mktmp)"
  cp "${PROJECT_CONFIG}" "${project_backup}"
  if [[ -f "${USER_GLOBAL_PATH}" ]]; then
    ug_backup="$(_mktmp)"
    cp "${USER_GLOBAL_PATH}" "${ug_backup}"
  else
    ug_backup=""
  fi

  _rollback_move() {
    cp "${project_backup}" "${PROJECT_CONFIG}"
    if [[ -n "${ug_backup}" ]]; then
      cp "${ug_backup}" "${USER_GLOBAL_PATH}"
    else
      \rm -f "${USER_GLOBAL_PATH}" 2>/dev/null
    fi
  }

  # user-global に既存キーあり + --overwrite: 既存削除してから追記
  if [[ "$overwrite" == "true" ]] && _user_global_has_key "$key"; then
    if ! _delete_key_in_file "${USER_GLOBAL_PATH}" "$section" "$leaf"; then
      echo "error:overwrite-delete-failed:${key}" >&2
      _rollback_move
      return 2
    fi
  fi

  # user-global に追記
  if ! _append_key_to_file "${USER_GLOBAL_PATH}" "$section" "$leaf" "$normalized"; then
    echo "error:user-global-append-failed:${key}" >&2
    _rollback_move
    return 2
  fi

  # project から削除
  if ! _delete_key_in_file "${PROJECT_CONFIG}" "$section" "$leaf"; then
    echo "error:project-delete-failed:${key}" >&2
    _rollback_move
    return 2
  fi

  printf 'move\t%s\t%s\tfrom_project\tto_user_global\n' "$key" "$value"
  return 0
}

# ─── サブコマンド: keep ─────────────────────────────

cmd_keep() {
  local key="$1"
  local dry_run="$2"
  local prefix=""
  if [[ "$dry_run" == "true" ]]; then
    prefix="dry-run:"
  fi

  if ! _is_individual_preference_key "$key"; then
    echo "error:invalid-key:${key}" >&2
    return 2
  fi

  printf '%skeep\t%s\n' "$prefix" "$key"
  return 0
}

# ─── 引数解析 + dispatch ───────────────────────────

main() {
  if [[ $# -lt 1 ]]; then
    echo "error:missing-subcommand" >&2
    exit 2
  fi

  local subcommand="$1"
  shift

  # オプション解析
  local key=""
  local overwrite="false"
  local dry_run="false"

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --overwrite)
        overwrite="true"
        shift
        ;;
      --dry-run)
        dry_run="true"
        shift
        ;;
      --*)
        echo "error:unknown-option:$1" >&2
        exit 2
        ;;
      *)
        if [[ -z "$key" ]]; then
          key="$1"
          shift
        else
          echo "error:extra-positional-arg:$1" >&2
          exit 2
        fi
        ;;
    esac
  done

  # dasel チェック
  if ! command -v dasel >/dev/null 2>&1; then
    echo "error:dasel-not-found" >&2
    exit 2
  fi

  _resolve_paths

  case "$subcommand" in
    detect)
      cmd_detect "$dry_run"
      exit $?
      ;;
    move)
      if [[ -z "$key" ]]; then
        echo "error:missing-key-arg:move" >&2
        exit 2
      fi
      cmd_move "$key" "$overwrite" "$dry_run"
      exit $?
      ;;
    keep)
      if [[ -z "$key" ]]; then
        echo "error:missing-key-arg:keep" >&2
        exit 2
      fi
      cmd_keep "$key" "$dry_run"
      exit $?
      ;;
    *)
      echo "error:unknown-subcommand:${subcommand}" >&2
      exit 2
      ;;
  esac
}

main "$@"
